### ISSUE TITLE
Error building the package 

### ISSUE THREAD

**Issue by okasha55** [ros-melodic-arch/ros-melodic-realtime-tools#2]
CMake Error at CMakeLists.txt:24 (target_link_libraries): Cannot specify link libraries for target "realtime_box_tests" which is not built by this project. 
can you help me with this error

**Comment by acxz** [comment]
@okasha55 sadly this is an issue that has been around for a while, we have made progress on it recently tho. Closing this issue as it is a duplicate of #1 . Maybe you can follow the conversation and help us out.
